spring.application.name=ddd-examples

# 외부 Bounded Context 서비스 주소
external.coupon.base-url=http://localhost:8081
external.product.base-url=http://localhost:8082
external.customer.base-url=http://localhost:8083
